---
GS_CREDENTIALS: /tmp/service_account.json
color_charts:
  COLUMN:
    -
      alpha: 1
      blue: 0.3
      green: 0.65
      red: 0.41
    -
      alpha: 1
      blue: 0.19
      green: 0.43
      red: 1.0
    -
      alpha: 1
      blue: 0.67
      green: 0.56
      red: 0.34
    -
      alpha: 1
      blue: 0.37
      green: 0.76
      red: 0.64
  LINE:
    -
      alpha: 1
      blue: 0
      green: 0
      red: 1.0
    -
      alpha: 1
      blue: 1
      green: 1
      red: 0
    -
      alpha: 1
      blue: 0
      green: 0.6
      red: 1
    -
      alpha: 1
      blue: 0.5
      green: 0.9
      red: 1.3
colors:
  tier1:
    alpha: 0.8
    blue: 0.8
    green: 0.6
    red: 0.7
  tier2:
    alpha: 1
    blue: 0.6
    green: 0.89
    red: 1
  tier3:
    alpha: 1
    blue: 0.95
    green: 0.88
    red: 0.81
  tier4:
    alpha: 1
    blue: 0.75
    green: 0.38
    red: 0.41
comp_colors:
  Ceph-Ansible:
    alpha: 1
    blue: 0.75
    green: 0.38
    red: 0.41
  Ceph-Mgr:
    alpha: 0.8
    blue: 0.8
    green: 0.6
    red: 0.7
  CephAdm:
    alpha: 1
    blue: 0.75
    green: 0.38
    red: 0.41
  CephFS:
    alpha: 1
    blue: 0.6
    green: 0.89
    red: 1
  Multi:
    alpha: 1
    blue: 0.95
    green: 0.88
    red: 0.81
  RADOS:
    alpha: 0.8
    blue: 0.8
    green: 0.6
    red: 0.7
  RBD:
    alpha: 1
    blue: 0.6
    green: 0.89
    red: 1
  RBD-Mirror:
    alpha: 1
    blue: 0.75
    green: 0.38
    red: 0.41
  RGW:
    alpha: 1
    blue: 0.95
    green: 0.88
    red: 0.81
  RGW-Multisite:
    alpha: 0.8
    blue: 0.8
    green: 0.6
    red: 0.7
  Web-UI:
    alpha: 1
    blue: 0.6
    green: 0.89
    red: 1
  iSCSI:
    alpha: 1
    blue: 0.95
    green: 0.88
    red: 0.81
component_filter:
  Automation:
    chartType: COLUMN
    keys: casecomponent.KEY
    labels:
      - RADOS
      - RBD
      - RGW
      - Ceph-Ansible
      - Ceph-Mgr
      - CephFS
      - iSCSI
      - RBD-Mirror
      - RGW-Multisite
      - Web-UI
      - Multi
      - CephAdm
    values:
      - RADOS
      - RBD
      - RGW
      - Ceph-Ansible
      - Ceph-Mgr
      - CephFS
      - iSCSI
      - RBD-Mirror
      - RGW-Multisite
      - Web-UI
      - Multi
      - CephAdm
data:
  tier1:
    Automation:
      chartType: COLUMN
      keys: caseautomation.KEY
      labels:
        - "Total Automated"
        - "Not Automated"
        - "Manual Only"
      values:
        - automated
        - notautomated
        - manualonly
  tier2:
    Automation:
      chartType: COLUMN
      keys: caseautomation.KEY
      labels:
        - "Total Automated"
        - "Not Automated"
        - "Manual Only"
      values:
        - automated
        - notautomated
        - manualonly
  tier3:
    Automation:
      chartType: COLUMN
      keys: caseautomation.KEY
      labels:
        - "Total Automated"
        - "Not Automated"
        - "Manual Only"
      values:
        - automated
        - notautomated
        - manualonly
  tier4:
    Automation:
      chartType: COLUMN
      keys: caseautomation.KEY
      labels:
        - "Total Automated"
        - "Not Automated"
        - "Manual Only"
      values:
        - automated
        - notautomated
        - manualonly
file_name: "RHCS Test"
key: tier.KEY
project_id: CEPH
recipient_user: ngangadh@redhat.com
sender_user: ceph-qe-infra@redhat.com
tags:
  - tier1
  - tier2
  - tier3
  - tier4
url: "https://polarion.engineering.redhat.com/polarion"
